--DB를 실행할 대 cmd는 끄면 아예 사용할 수 ㅇ없다. 그래서 키고 코드를 작성해야 한다.


--만약에 파일이 있다면 지워라.
drop table if exists member CASCADE;

--파일을 생성한다.
--id, name, primary key는 id이다.
create table member
(
--generated by default as identity: 주요한 부분
--만약 id가 셋팅되지 않고 null로 들어오면 자동으로 id값을 채워준다.
id bigint generated by default as identity,
name varchar (255),
primary key (id)
);


--멤버 name에 spring으로 추가해라
insert into member(name) values('spring');
insert into member(name) values('spring2');
--위와 같이 2문장을 적어주면 name에 spring이랑 spring2가 들어있음을 알 수 있음.